#include QMK_KEYBOARD_H





const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	[0]=LAYOUT_all(
		MT(KC_ESC, KC_Q), KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, 
		KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_ENT, 
		KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, 
		KC_LGUI, KC_LCTL, KC_LALT, DF(0), KC_SPC, KC_SPC, DF(1), DF(2), KC_TAB, KC_BSPC),

	[1]=LAYOUT_all(
		KC_1, KC_2, KC_3, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_RBRC, KC_LBRC, KC_EQUAL, 
		KC_4, KC_5, KC_6, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_RPRN, KC_LPRN, KC_ENT, 
		MT(KC_LSFT, KC_7), KC_8, KC_9, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_RCBR, KC_LCBR, KC_GRAVE, 
		KC_LGUI, MT(KC_LCTL,KC_0), KC_LALT, DF(0), KC_SPC, KC_SPC, DF(1), DF(2), KC_TRNS, KC_BSPC),
	[2]=LAYOUT_all(
		KC_SYSTEM_WAKE, MT(KC_SYSTEM_POWER,KC_SYSTEM_SLEEP), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_MEDIA_PREV_TRACK, KC_MEDIA_PLAY_PAUSE, KC_MEDIA_NEXT_TRACK, KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_UP, KC_DOWN, KC_RIGHT, 
		KC_TRNS, KC_TRNS, KC__VOLDOWN, KC__VOLUP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
	

	};
